### ISSUE TITLE
DLP to run on the data within an existing Big Query table

### ISSUE THREAD

**Issue by bayareala8s** [GoogleCloudPlatform/dlp-dataflow-deidentification#72]
We have a use-case where we want to run DLP process inspect, deidentify, reidentify for a BigQuery Table solely within Big Query space E.g Big Query Stored procedures or with Big Query commands & script. Wondering how we can achieve that.

We do not want to use the DataFlow or any other GCP services for DLP.

Appreciate your help and support.

Himanshu

**Comment by santhh** [comment]
Hi Himanshu- You can only do  table inspection out of BQ at this time. There is no support for de-identification which is why you would need dataflow. Some helpful links:
https://cloud.google.com/dlp/docs/inspecting-storage#dlp-inspect-bigquery-console
https://cloud.google.com/blog/products/data-analytics/scan-bigquery-for-sensitive-data-using-cloud-dlp
